"use client"

import { Check, Moon, Sun, UserRound } from "lucide-react"
import { useTheme } from "next-themes"
import { Button } from "@workspace/ui/components/button"
import { useAuthStore } from "@/store/auth-store"

export function SettingsModule() {
  const { user } = useAuthStore(); const { theme, setTheme } = useTheme()
  return <div className="mx-auto grid max-w-4xl gap-6"><div><p className="text-sm font-medium text-muted-foreground">Workspace</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Settings</h1><p className="mt-2 text-sm text-muted-foreground">Manage your account preferences.</p></div><section className="overflow-hidden rounded-2xl border bg-background"><div className="border-b p-5"><h2 className="font-semibold">Account</h2><p className="mt-1 text-sm text-muted-foreground">Your signed-in account details.</p></div><div className="flex items-center gap-4 p-5"><div className="grid size-11 place-items-center rounded-full bg-primary text-primary-foreground"><UserRound className="size-5" /></div><div><p className="font-medium">{user?.name}</p><p className="text-sm text-muted-foreground">{user?.email}</p></div></div></section><section className="overflow-hidden rounded-2xl border bg-background"><div className="border-b p-5"><h2 className="font-semibold">Appearance</h2><p className="mt-1 text-sm text-muted-foreground">Choose how Nucleus looks on this device.</p></div><div className="grid gap-3 p-5 sm:grid-cols-2"><Button variant={theme === "light" ? "secondary" : "outline"} className="h-auto justify-start gap-3 p-4" onPress={() => setTheme("light")}><Sun className="size-5" /><span className="grid text-left"><span className="font-medium">Light</span><span className="text-xs text-muted-foreground">Bright and clear</span></span>{theme === "light" && <Check className="ml-auto size-4" />}</Button><Button variant={theme === "dark" ? "secondary" : "outline"} className="h-auto justify-start gap-3 p-4" onPress={() => setTheme("dark")}><Moon className="size-5" /><span className="grid text-left"><span className="font-medium">Dark</span><span className="text-xs text-muted-foreground">Easy on the eyes</span></span>{theme === "dark" && <Check className="ml-auto size-4" />}</Button></div></section></div>
}
