"use client"
import { Clock3, LogIn, LogOut } from "lucide-react"
import { useState } from "react"
import { Button } from "@workspace/ui/components/button"
import { useStaff } from "@/hooks/use-staff"
import { useAttendance, useAttendanceMutations } from "@/hooks/use-phase-two"
import { useToast } from "@/providers/toast-provider"
import { getApiErrorMessage } from "@/lib/api-error"
export function AttendanceModule() { const {toast}=useToast(); const [staffId,setStaffId]=useState(""); const {data:staff}=useStaff({}); const {data,isLoading}=useAttendance(); const {clockIn,clockOut}=useAttendanceMutations(); const members=staff?.data??[]; const selected=Number(staffId); const run=async(fn:()=>Promise<unknown>,title:string)=>{try{await fn();toast({tone:"success",title})}catch(e){toast({tone:"error",title:"Unable to update attendance",description:getApiErrorMessage(e)})}}; return <div className="mx-auto grid max-w-6xl gap-6"><div><p className="text-sm font-medium text-muted-foreground">Daily operations</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Attendance</h1><p className="mt-2 text-sm text-muted-foreground">Track staff check-in and check-out times.</p></div><section className="flex flex-col gap-3 rounded-2xl border bg-background p-5 sm:flex-row sm:items-end"><div className="grid flex-1 gap-2"><label htmlFor="attendance-staff" className="text-sm font-medium">Staff member</label><select id="attendance-staff" value={staffId} onChange={e=>setStaffId(e.target.value)} className="h-11 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-3 focus:ring-ring/20"><option value="">Select a staff member</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div><Button isDisabled={!selected||clockIn.isPending} onPress={()=>run(()=>clockIn.mutateAsync(selected),"Staff clocked in")}><LogIn/>Clock in</Button></section><section className="overflow-hidden rounded-2xl border bg-background"><div className="border-b p-5"><h2 className="font-semibold">Attendance history</h2></div>{isLoading?<div className="p-8 text-sm text-muted-foreground">Loading attendance…</div>:<div className="overflow-x-auto"><table className="w-full min-w-[42rem] text-left text-sm"><thead className="border-b bg-muted/30 text-xs text-muted-foreground"><tr><th className="px-5 py-3">Staff</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Check in</th><th className="px-5 py-3">Check out</th><th className="px-5 py-3">Action</th></tr></thead><tbody className="divide-y">{(data?.data??[]).map(item=><tr key={item.id}><td className="px-5 py-4 font-medium">{item.staff_name}</td><td className="px-5 py-4 text-muted-foreground">{item.work_date}</td><td className="px-5 py-4">{item.check_in??"—"}</td><td className="px-5 py-4">{item.check_out??"—"}</td><td className="px-5 py-4">{item.check_out?<span className="text-xs text-muted-foreground">Completed</span>:<Button size="sm" variant="outline" onPress={()=>run(()=>clockOut.mutateAsync(item.id),"Staff clocked out")}><LogOut/>Clock out</Button>}</td></tr>)}</tbody></table>{!data?.data?.length&&<div className="grid place-items-center p-10 text-center"><Clock3 className="size-8 text-muted-foreground"/><p className="mt-3 text-sm text-muted-foreground">No attendance records yet.</p></div>}</div>}</section></div> }
